### ISSUE TITLE
現コントラクトの構成要素の説明と切り分け

### ISSUE THREAD

**Issue by 0xHaku** [DeFiGeek-Community/comet#2]

**Comment by 0xHaku** [comment]
![image](https://github.com/DeFiGeek-Community/comet/assets/32897506/9efe533c-816d-4cd9-ae14-c20a22050a57)

**Comment by 0xHaku** [comment]
![image](https://github.com/DeFiGeek-Community/comet/assets/32897506/3a4bae47-8636-44b2-930e-f54cbd9851c0)

**Comment by norwegianneko** [comment]
<H2> 1. cometの主なコントラクト</H2>
<h3>Comet.sol</h3>
inheritance:CometMainInterface<br>
Compound v3のメインとなるコントラクト。<br>
CometProxyコントラクトからデリゲートコールで参照される。

<h3> CometConfiguration.sol </h3>
inheritance:なし<br>
Comet.sol及びCometExt.solのコンストラクタに渡されるstruct型データを定義するコントラクト。

<h3> CometCore.sol </h3>
inheritance:CometConfiguration, CometStorage, CometMath<br>
Comet.solとCometExt.solで用いられる関数と定数を含むアブストラクトコントラクト。

<h3> CometExt.sol </h3>
inheritance:CometExtInterface<br>
Comet.solに収まらない追加の機能の実装を行うコントラクト。<br>
Comet.solからデリゲートコールで参照される。
実装内容としては変数の読み取り、書き込みはapprove周りのテンプレート系。<br>
CometExtはupgradeabilityが無いため、脆弱性などの不安が少ない部分を固めていると考えられる。<br>
（そもそもなぜCometと分けているのか不明だが、compound teamの発言で「CometFactory is the main bottleneck」とあり、コントラクト容量的にCometに収まらない機能をCometExtで実装していると考えられる）

<h3> CometExtInterface.sol </h3>
inheritance:CometCore<br>
CometExt.solのすべての関数とイベントを含むアブストラクトコントラクト。

<h3> CometFactory.sol </h3>
inheritance:CometConfiguration<br>
新しいCometを作るためのファクトリーコントラクト。

<h3> CometInterface.sol </h3>
inheritance:CometMainInterface, CometExtInterface<br>
2つのインターフェースを継承するアブストラクトコントラクト。

<h3> CometMainInterface.sol </h3>
inheritance:CometCore<br>
Comet.solのすべての関数とイベントを含むアブストラクトコントラクト。

<h3> CometMath.sol </h3>
inheritance:なし<br>
Cometのコードベース全体で使用されるmath関数（数値チェック）を定義するコントラクト。

<h3> CometProxyAdmin.sol </h3>
inheritance:ProxyAdmin<br>
Comet.solをアップグレードする際に用いるコントラクト。

<h3> CometStorage.sol </h3>
inheritance:なし<br>
Cometで使用するストレージ変数を定義するコントラクト。

<h3> Configurator.sol </h3>
inheritance:ConfiguratorStorage<br>
Cometの設定を管理し、CometFactory.solを呼び出してCometのデプロイを行うコントラクト。

<h3> ConfiguratorProxy.sol </h3>
inheritance:TransparentUpgradeableProxy<br>
Configurator.solのプロキシコントラクト。

<h3> ConfiguratorStorage.sol </h3>
inheritance:CometConfiguration<br>
Configurator.solで用いるストレージ変数を定義するコントラクト。

<H2> 2. 精算・リワード関係のコントラクト</H2>
<h3> OnChainLiquidator.sol </h3>
inheritance:IUniswapV3FlashCallback, PeripheryImmutableState, PeripheryPayments<br>
精算に関するコントラクト。<br>
（デプロイは確認出来なかったが、Compound teamはデプロイしていると言っている）

<h3> CometRewards.sol </h3>
inheritance:なし<br>
Cometのユーザーがプロトコルの利用に応じて報酬を請求できるようにするコントラクト。

<H2> 3. トークンやプライスフィードに関するコントラクト </H2>
<h3>MultiplicativePriceFeed.sol </h3>
inheritance:IPriceFeed<br>
2つのChainlinkプライスフィードから価格を取得し、それらの価格を掛け合わせて新しい価格を計算するコントラクト。

<h3>WBTCPriceFeed.sol </h3>
inheritance:IPriceFeed<br>
BTC/USD価格とWBTC/BTC価格を掛け合わせてWBTC/USD価格を計算するコントラクト。

<h3> ERC20.sol </h3>
inheritance:なし<br>
ERC20トークンに関するインターフェース。

<h3> IPriceFeed.sol </h3>
inheritance:なし<br>
プライスフィードに関するインターフェース。

<h3> IWETH9.sol </h3>
inheritance:なし<br>
WETHに関するインターフェース。

<h3> ScalingPriceFeed.sol </h3>
inheritance:IPriceFeed<br>
チェーンリンクから得たプライスのスケールアップ・ダウンを行うコントラクト。

<h3> ConstantPriceFeed.sol </h3>
inheritance:IPriceFeed<br>
固定された価格を提供するモックコントラクト。

<h3> WstETHPriceFeed.sol </h3>
inheritance:IPriceFeed<br>
ChainlinkのstETH / ETHの価格フィードとwstETHの価格スケールを使用してwstETHトークンの価格を計算するコントラクト。

<h3> IWstETH.sol </h3>
inheritance:ERC20.sol<br>
wstETHに関するインターフェース。

<h3> IERC20NonStandard.sol </h3>
inheritance:なし<br>
返り値を持たないタイプのERC20トークンに関するインターフェース。

<h3> IComp.sol </h3>
inheritance:ERC20<br>
COMPトークンに関するインターフェース。

<H2> 4. 補助的なコントラクト </H2>
<h3> BaseBulker.sol </h3>
inheritance:なし<br>
複数のTx（例えば担保の差し入れとベーストークンの借り入れ）を1つにまとめるコントラクト。

<h3> MainnetBulker.sol </h3>
inheritance:BaseBulker<br>
メインネット特有のstETH、wstETHに関する複数のTxを一つにまとめるコントラクト。

<h3> IProxy.sol </h3>
inheritance:なし<br>
プロキシコントラクトに関するインターフェース。<br>
（しかしながら、TransparentUpGrade Proxyでは用いられていない）

<h3> BaseBridgeReceiver.sol </h3>
inheritance:BaseBridgeReceiver<br>
ブリッジに関するコントラクト。

<h3> SweepableBridgeReceiver.sol </h3>
inheritance:BaseBridgeReceiver<br>
ブリッジ送金時にアクシデントが起きた際にトークンを回収するコントラクト。

<H2> 5. ガバナンスに関するコントラクト </H2>
<h3> IGovernorBravo.sol </h3>
inheritance:なし<br>
Governor Bravoと呼ばれるガバナンスプロトコルに関するインターフェース。

<h3> ITimelock.sol </h3>
inheritance:なし<br>
CompoundのオンチェーンガバナンスのTimelockに関するインターフェース。

**Comment by norwegianneko** [comment]
依存関係はこちら
https://github.com/DeFiGeek-Community/comet/blob/doc/docs/inheritance_all.md
