### ISSUE TITLE
各種コンフィグの説明と設定値の確認

### ISSUE THREAD

**Issue by 0xHaku** [DeFiGeek-Community/comet#3]

**Comment by 0xHaku** [comment]
# CometConfiguration

## ExtConfiguration
- bytes32 name32;
  - ベーストークンをラップするときのトークン名
- bytes32 symbol32;
  - ベーストークンをラップするときのシンボル名

## Configuration 
https://docs.compound.finance/helper-functions/#get-protocol-configuration

- address governor;
  - プールのガバナー
- address pauseGuardian;
  - プールの停止専用権限
- address baseToken;
  - ベーストークン
- address baseTokenPriceFeed;
  - ベーストークンの価格フィード
- address extensionDelegate;
  - CometExtのアドレス
- uint64 supplyKink;
  - 貸出の低金利スロープと高金利スロープの閾値となる利用率の閾値
  - 範囲：0〜1E+18（利用率は100%が上限として）
  - 1e18でスケールされる
- uint64 supplyPerYearInterestRateSlopeLow;
  - 低金利スロープの年利率(y=ax+bのa)
  - 範囲：0〜2^64（約1.8E+19）
  - 1e18でスケールされる
- uint64 supplyPerYearInterestRateSlopeHigh;
  - 高金利スロープの年利率(y=ax+bのa)
  - 範囲：0〜2^64（約1.8E+19）
  - 1e18でスケールされる
- uint64 supplyPerYearInterestRateBase;
  - 低金利スロープと高金利スロープの基礎値(y=ax+bのb)
  - 範囲：0〜2^64（約1.8E+19）
  - 1e18でスケールされる
- uint64 borrowKink;
  - 借入の低金利スロープと高金利スロープの閾値となる利用率の閾値
  - 範囲：0〜1E+18（利用率は100%が上限として）
- uint64 borrowPerYearInterestRateSlopeLow;
  - 低金利スロープの年利率(y=ax+bのa)
  - 範囲：0〜2^64（約1.8E+19）
  - 1e18でスケールされる
- uint64 borrowPerYearInterestRateSlopeHigh;
  - 低金利スロープの年利率(y=ax+bのa)
  - 範囲：0〜2^64（約1.8E+19）
  - 1e18でスケールされる
- uint64 borrowPerYearInterestRateBase;
  - 低金利スロープと高金利スロープの基礎値(y=ax+bのb)
  - 範囲：0〜2^64（約1.8E+19）
  - 1e18でスケールされる
- uint64 storeFrontPriceFactor;
  - 清算ペナルティのうち、プロトコルの代わりに清算者に支払われる割合
  - 範囲：storeFrontPriceFactor＜FACTOR_SCALE(1E+18)
  - 1e18でスケールされる
- uint64 trackingIndexScale;
  - 報酬計算用のスケーラー
  - 範囲：0〜2^64（約1.8E+19）
- uint64 baseTrackingSupplySpeed;
  - 貸出向け報酬配布速度
  - 範囲：0〜2^64（約1.8E+19）
  - 1日に配布したい量*86400/trackingIndexScale
- uint64 baseTrackingBorrowSpeed;
  - 借入向け報酬配布速度
  - 範囲：0〜2^64（約1.8E+19）
  - 1日に配布したい量*86400/trackingIndexScale
- uint104 baseMinForRewards;
  - 貸出されるベーストークンの報酬が発生する最小量
  - 範囲：0〜2^104（ゼロは含まない）
- uint104 baseBorrowMin;
  - 借入の最小量
  - 範囲：0〜2^104（約2E+31）
- uint104 targetReserves;
  - 担保を売却できるリザーブの閾値
  - 範囲：0〜2^104（約2E+31）
- AssetConfig[] assetConfigs;
  - 担保トークンの設定（後述）

## AssetConfig 
https://docs.compound.finance/helper-functions/#get-asset-info

- address asset;
  - アセット
- address priceFeed;
  - アセットの価格フィード
- uint8 decimals;
  - アセットのデシマル
- uint64 borrowCollateralFactor;
  - 借入可能な担保価値の割合
  - 1e18でスケールされる
- uint64 liquidateCollateralFactor;
  - 清算可能になるまで借入可能な担保価値の割合
  - 1e18でスケールされる
- uint64 liquidationFactor;
  - 清算のペナルティ
  - 1e18でスケールされる
- uint128 supplyCap;
  - 担保資産の供給上限

**Comment by norwegianneko** [comment]
| ExtConfiguration  | name / symbol (string) |
| ------------- | ------------- |
| name32  | Compound USDC |
| symbol32  | cUSDCv3 |

bytesにはethers.utils.formatBytes32String("")で変換

| BaseToken Configuration (USDC) | Address / Parameter |
| ------------- | ------------- |
| governor  | 0x6d903f6003cca6255D85CcA4D3B5E5146dC33925|
| pauseGuardian  | 0xbbf3f1421D886E9b2c5D716B5192aC998af2012c |
| baseToken | 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48 |
| baseTokenPriceFeed | 0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6 |
| extensionDelegate | 0x285617313887d43256F852cAE0Ee4de4b68D45B0 |
| supplyKink | 9.50E+17 |
| supplyPerYearInterestRateSlopeLow | 3.40E+16 |
| supplyPerYearInterestRateSlopeHigh | 7.60E+17 |
| supplyPerYearInterestRateBase | 0 |
| borrowKink | 9.50E+17 |
| borrowPerYearInterestRateSlopeLow | 3.33E+16 |
| borrowPerYearInterestRateSlopeHigh | 5.67E+17 |
| borrowPerYearInterestRateBase | 1.00E+16 |
| storeFrontPriceFactor | 6.00E+17 |
| trackingIndexScale | 1.00E+15 |
| baseTrackingSupplySpeed | 1.16E+12 |
| baseTrackingBorrowSpeed | 4.41E+12 |
| baseMinForRewards | 1.00E+12 |
| baseBorrowMin | 1.00E+08 |
| targetReserves | 5.00E+12 |


| assetConfig (COMP) | Address / Parameter |
| ------------- | ------------- |
| asset | 0xc00e94Cb662C3520282E6f5717214004A7f26888 |
| priceFeed | 0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5 |
| decimals | 18 |
| borrowCollateralFactor | 6.50E+17 |
| liquidateCollateralFactor | 7.00E+17 |
| liquidationFactor | 8.80E+17 |
| supplyCap | 9.00E+23 |

| assetConfig (WBTC) | Address / Parameter |
| ------------- | ------------- |
| asset | 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599 |
| priceFeed | 0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c |
| decimals | 8 |
| borrowCollateralFactor | 7.00E+17 |
| liquidateCollateralFactor | 7.70E+17 |
| liquidationFactor | 9.50E+17 |
| supplyCap | 1.80E+12 |

| assetConfig (WETH) | Address / Parameter |
| ------------- | ------------- |
| asset | 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 |
| priceFeed | 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419 |
| decimals | 18 |
| borrowCollateralFactor | 8.25E+17 |
| liquidateCollateralFactor | 8.95E+17 |
| liquidationFactor | 9.50E+17 |
| supplyCap | 5.00E+23 |

| assetConfig (UNI) | Address / Parameter |
| ------------- | ------------- |
| asset | 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984 |
| priceFeed | 0x553303d460EE0afB37EdFf9bE42922D8FF63220e |
| decimals | 18 |
| borrowCollateralFactor | 7.50E+17 |
| liquidateCollateralFactor | 8.10E+17 |
| liquidationFactor | 9.30E+17 |
| supplyCap | 6.00E+24 |

| assetConfig (LINK) | Address / Parameter |
| ------------- | ------------- |
| asset | 0x514910771AF9Ca656af840dff83E8264EcF986CA |
| priceFeed | 0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c |
| decimals | 18 |
| borrowCollateralFactor | 7.90E+17 |
| liquidateCollateralFactor | 8.50E+17 |
| liquidationFactor | 9.30E+17 |
| supplyCap | 4.00E+24 |

ソース：Configrator(0x316f9708bB98af7dA9c68C1C3b5e79039cD336E3)のgetConfiguration関数にCometProxyアドレス(0xc3d688B66703497DAA19211EEdff47f25384cdc3)を入力
