### ISSUE TITLE
運用にむけたコントラクト構成の説明

### ISSUE THREAD

**Issue by 0xHaku** [DeFiGeek-Community/comet#7]

**Comment by norwegianneko** [comment]
![image](https://github.com/DeFiGeek-Community/comet/assets/81135479/7b6b77f4-aa43-453c-a61a-df274f8740e6)

**Comment by norwegianneko** [comment]
コントラクト構成について議論した結果、以下の通りとなった。
- ガバナンスはsafeによる管理とし、GovernorBravo（GovSimple）は用いない。
- 実行までの遅延は投票における確認期間があるため、Timelockは用いない。
- Configuratorは各種パラメータをセットし、コミュニティに確認するためのコントラクト、ProxyAdminはCometProxyへのupgradeTo関数のcallとConfiguratorへのdeploy関数のcallのTxを1つにまとめる役割であり、DFGCではパラメータの確認は投票、管理はsafeで行うことからProxyAdmin〜ConfiguratorProxy〜ConfiguratorImplは用いない。

上記を反映した図はこちら
https://github.com/DeFiGeek-Community/comet/blob/main/docs/composition.md
